version: '3.8'

# TODO: Read from .env (if possible)

services:
    postgres-auth:
        image: postgres:17.0
        container_name: postgres-auth
        environment:
            POSTGRES_DB: ${AUTH_DATABASE_DB_NAME}
            POSTGRES_USER: ${AUTH_DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${AUTH_DATABASE_PASSWORD}
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - pgdata-auth:/var/lib/postgresql/data
        ports:
            - '${AUTH_DATABASE_PORT}:5432'
        command: postgres -c 'listen_addresses=*'

    postgres-order:
        image: postgres:17.0
        container_name: postgres-order
        environment:
            POSTGRES_DB: ${ORDER_DATABASE_DB_NAME}
            POSTGRES_USER: ${ORDER_DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${ORDER_DATABASE_PASSWORD}
        volumes:
            - pgdata-order:/var/lib/postgresql/data
        ports:
            - '${ORDER_DATABASE_PORT}:5432'

    redis:
        image: redis:7.4.1
        container_name: redis
        ports:
            - '${REDIS_PORT}:6379'
        volumes:
            - redis-data:/data

volumes:
    pgdata-auth:
    pgdata-order:
    redis-data:
