// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: libs/proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface UserSignupInterface {
  username: string;
  password: string;
  email: string;
}

export interface UserSigninInterface {
  username: string;
  password: string;
}

export interface SignupResponse {
  data: string;
  success: boolean;
  error: ErrorInterface | undefined;
}

export interface SigninResponse {
  data: TokensInterface | undefined;
  success: boolean;
  error: ErrorInterface | undefined;
}

export interface TokensInterface {
  accessToken: string;
  refreshToken: string;
}

export interface UserModel {
  id: string;
  createdAt: string;
  updatedAt: string;
  username: string;
  password: string;
  email: string;
  role: string;
}

export interface ErrorInterface {
  statusCode: number;
  message: string;
}

export const USER_PACKAGE_NAME = "user";

export interface UsersServiceClient {
  signup(request: UserSignupInterface): Observable<SignupResponse>;

  signin(request: UserSigninInterface): Observable<SigninResponse>;
}

export interface UsersServiceController {
  signup(request: UserSignupInterface): Promise<SignupResponse> | Observable<SignupResponse> | SignupResponse;

  signin(request: UserSigninInterface): Promise<SigninResponse> | Observable<SigninResponse> | SigninResponse;
}

export function UsersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["signup", "signin"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "UsersService";
