// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.12.4
// source: libs/proto/common.proto

/* eslint-disable */

export const protobufPackage = "common";

export interface ErrorInterface {
  statusCode: number;
  message: string;
}

export const COMMON_PACKAGE_NAME = "common";
