// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.12.4
// source: libs/proto/market-data.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty, ErrorInterface } from "./common";

export const protobufPackage = "market_data";

export interface GoldPriceResponse {
  data: GoldPriceDataProtoType | undefined;
  success: boolean;
  error: ErrorInterface | undefined;
}

export interface GoldPriceDataProtoType {
  timestamp: number;
  metal: string;
  currency: string;
  exchange: string;
  symbol: string;
  prevClosePrice: number;
  openPrice: number;
  lowPrice: number;
  highPrice: number;
  openTime: number;
  price: number;
  ch: number;
  chp: number;
  ask: number;
  bid: number;
  priceGram24k: number;
  priceGram22k: number;
  priceGram21k: number;
  priceGram20k: number;
  priceGram18k: number;
  priceGram16k: number;
  priceGram14k: number;
  priceGram10k: number;
}

export const MARKET_DATA_PACKAGE_NAME = "market_data";

export interface MarketDataServiceClient {
  getGoldPrice(request: Empty): Observable<GoldPriceResponse>;
}

export interface MarketDataServiceController {
  getGoldPrice(request: Empty): Promise<GoldPriceResponse> | Observable<GoldPriceResponse> | GoldPriceResponse;
}

export function MarketDataServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getGoldPrice"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MarketDataService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MarketDataService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MARKET_DATA_SERVICE_NAME = "MarketDataService";
