// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.12.4
// source: libs/proto/order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty, ErrorInterface } from "./common";

export const protobufPackage = "order";

export interface CreateInvoiceInterface {
  customerId: string;
  goldGrams: string;
  amount: number;
}

export interface CreateInvoiceResponse {
  data: InvoiceType | undefined;
  success: boolean;
  error: ErrorInterface | undefined;
}

export interface GetInvoiceListResponse {
  data: InvoiceType[];
  success: boolean;
  error: ErrorInterface | undefined;
}

export interface InvoiceType {
  id: string;
  createdAt: string;
  updatedAt: string;
  customerId: string;
  goldGrams: string;
  amount: number;
  gramPrice: number;
  totalPrice: number;
}

export const ORDER_PACKAGE_NAME = "order";

export interface OrderServiceClient {
  createInvoice(request: CreateInvoiceInterface): Observable<CreateInvoiceResponse>;

  getInvoiceList(request: Empty): Observable<GetInvoiceListResponse>;
}

export interface OrderServiceController {
  createInvoice(
    request: CreateInvoiceInterface,
  ): Promise<CreateInvoiceResponse> | Observable<CreateInvoiceResponse> | CreateInvoiceResponse;

  getInvoiceList(
    request: Empty,
  ): Promise<GetInvoiceListResponse> | Observable<GetInvoiceListResponse> | GetInvoiceListResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createInvoice", "getInvoiceList"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
